name: Continuous

on: 
  push:
  create:
    tags:

jobs:

  linux-mac:
    strategy:
      matrix:
        cfg: [{os: ubuntu-latest, cxx: g++-12},
              {os: ubuntu-latest, cxx: g++-9},
              {os: macos-latest, cxx: clang++}]
        config: [Release, Debug]

    runs-on:  ${{ matrix.cfg.os }}

    env:
      CXX: ${{ matrix.cfg.cxx }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: CMake Build
      run: cmake --build build --parallel

    - name: Run executable
      run: build/bin/parameter-example --show-params

    -
      name: Deploy
      uses: xresloader/upload-to-github-release@v1
      with:
        tags: true
        draft: false
        file: param_parser/param_parser.h
        overwrite: false
        update_latest_release: true
        verbose: true

  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build

    - name: Release build
      run: cmake --build build --parallel --config Release

    - name: Release run
      run: build/bin/Release/parameter-example.exe --show-params

    - name: Debug build
      run: cmake --build build --parallel --config Debug

    - name: Debug run
      run: build/bin/Debug/parameter-example.exe --show-params

    -
      name: Deploy
      uses: xresloader/upload-to-github-release@v1
      with:
        tags: true
        draft: false
        file: param_parser/param_parser.h
        overwrite: false
        update_latest_release: true
        verbose: true